require("bytze.keymaps")
require("bytze.plugins.lazy")
require("bytze.options")

require("bytze.plugins.misc")
require("bytze.plugins.dap")
require("bytze.plugins.gitsigns")
require("bytze.plugins.colors")
require("bytze.plugins.telescope")
require("bytze.plugins.treesitter")
require("bytze.plugins.lsp")
require("bytze.plugins.trouble")
require("bytze.plugins.undotree")
require("bytze.plugins.whichkey")